import Head from 'next/head'
import Image from 'next/image'
import { PostCard, Categories, PostWidget } from '../components';
import styles from '../styles/Home.module.scss'
// import styles from '../styles/main.scss'
// import 'bootstrap/dist/css/bootstrap.css';

import { getPosts } from '../services'

// demo posts
// const posts = [
//   {title: 'react testing', excerpt: 'learn react testing'},
//   {title: 'react testing2', excerpt: 'learn react testing2'},
//   {title: 'react testing3', excerpt: 'learn react testing3'}
// ];


export default function Home({posts}) {
  return (
    <div className="container-fluid mx-auto px-5 mb-1">
      <Head>
        <title>roxiverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* change these cdns */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>
      <div > 
          <main className="container row m-0 p-0">
          <div className="col-9">
          {posts.map((post) => <PostCard post={post.node} key={post.title} />)}
        </div>
        <div className="col-3">
        <div className="row">
        <div className="col-12">
            <PostWidget/>
          </div>
          <div className="col-12">
            <Categories/>
          </div>
        </div>
        </div>
        {/* guessing this is the body */}
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
        </main>
      </div>

      

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps(){ // special function that will get our posts and allows us to pass them as props to the Home component
  const posts = (await getPosts()) || []; // return empty if getPosts fails or returns nothing
  return {
    props: {posts}
  }
}